"""Nix integration helpers shared across build stages."""

from __future__ import annotations

import shlex
import textwrap


def nix_wrap(cmd: str, nix: dict | None) -> str:
    """Wrap a shell command with ``nix develop`` if nix is enabled.

    *nix* is the ``nix`` dict from IterationConfig (``{"enabled": bool, "flake": str}``).
    Returns *cmd* unchanged when nix is disabled or *nix* is None.
    """
    if not nix or not nix.get("enabled"):
        return cmd
    flake = shlex.quote(nix.get("flake", ".#devShell"))
    return f"nix develop {flake} --command bash -c {shlex.quote(cmd)}"


# ── Package lists ────────────────────────────────────────────────────────

_KERNEL_PACKAGES = """\
          # Kernel build
          gcc gnumake flex bison bc perl
          openssl openssl.dev
          elfutils ncurses pkg-config
          cpio gzip"""

_QEMU_PACKAGES = """\
          # QEMU build
          glib pixman meson ninja python3"""

_RUNTIME_PACKAGES = """\
          # Runtime
          qemu socat tmux"""


# ── Flake generator ─────────────────────────────────────────────────────

def generate_nix_flake(
    *,
    include_qemu_deps: bool = True,
    include_runtime: bool = True,
) -> str:
    """Return a default ``flake.nix`` for the FastTrack dev shell.

    Parameters
    ----------
    include_qemu_deps:
        Include packages needed to build QEMU from source (glib, pixman, etc.).
    include_runtime:
        Include runtime tools (qemu, socat, tmux).
    """
    package_blocks = [_KERNEL_PACKAGES]
    if include_qemu_deps:
        package_blocks.append(_QEMU_PACKAGES)
    if include_runtime:
        package_blocks.append(_RUNTIME_PACKAGES)
    packages = "\n".join(package_blocks)

    return textwrap.dedent(f"""\
        {{
          description = "FastTrack — kernel iteration dev shell";

          inputs = {{
            nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
          }};

          outputs = {{ self, nixpkgs }}:
            let
              systems = [ "x86_64-linux" "aarch64-linux" ];
              forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f system);
            in {{
              devShells = forAllSystems (system:
                let
                  pkgs = import nixpkgs {{ inherit system; }};
                in {{
                  default = pkgs.mkShell {{
                    packages = with pkgs; [
        {packages}
                    ];
                    # Nix hardening flags break the kernel build
                    hardeningDisable = [ "all" ];

                    shellHook = ''
                      export KBUILD_BUILD_USER="fasttrack"
                      export KBUILD_BUILD_HOST="nix"
                    '';
                  }};
                }});
            }};
        }}
    """)


# ── NixOS rootfs config generator ───────────────────────────────────────

def generate_nix_rootfs(*, initramfs: bool = False) -> str:
    """Return a minimal NixOS ``configuration.nix`` for a QEMU guest.

    Parameters
    ----------
    initramfs:
        If True, produce a config suited for an initramfs/cpio rootfs
        (smaller, busybox-oriented, no disk mounts).
        If False, produce a config for a disk image (qcow2/raw).
    """
    if initramfs:
        return textwrap.dedent("""\
            # Auto-generated by FastTrack — minimal NixOS initramfs guest.
            # Use with: rootfs.type = "nixos" + nested virtualization (cpio mode).
            { config, pkgs, lib, modulesPath, ... }:

            {
              documentation.enable = false;

              boot.kernelParams = [ "console=ttyS0" "nokaslr" ];

              # Initramfs-only: use busybox for a tiny footprint
              environment.systemPackages = with pkgs; [
                busybox
              ];

              services.getty.autologinUser = "root";
              users.users.root.initialHashedPassword = "";

              system.stateVersion = "24.11";
            }
        """)

    return textwrap.dedent("""\
        # Auto-generated by FastTrack — minimal NixOS guest configuration.
        # Use with: rootfs.type = "nixos" in config.yaml.
        # Note: qemu-guest.nix and boot.loader.grub are handled by the
        # FastTrack builder expression — do not re-import them here.
        { config, pkgs, lib, modulesPath, ... }:

        {
          documentation.enable = false;

          boot.kernelParams = [ "console=ttyS0" ];

          # Auto-login on serial console for non-interactive testing
          services.getty.autologinUser = "root";

          networking.useDHCP = true;

          environment.systemPackages = with pkgs; [
            coreutils util-linux procps iproute2
            strace ltrace vim
          ];

          services.openssh = {
            enable = true;
            settings.PermitRootLogin = "yes";
            settings.PermitEmptyPasswords = "yes";
          };

          users.users.root.initialHashedPassword = "";

          fileSystems."/" = lib.mkDefault {
            device = "/dev/vda";
            fsType = "ext4";
          };

          system.stateVersion = "24.11";
        }
    """)


# ── NixOS initramfs builder expression ──────────────────────────────────

def generate_nix_initramfs_builder(config_path: str) -> str:
    """Return a Nix expression that builds a cpio.gz initramfs from a NixOS config.

    This complements ``_NIXOS_IMAGE_NIX`` in ``stages/rootfs.py`` which
    builds disk images.  This one produces ``system.build.initialRamdisk``
    for use with nested virtualization (QEMU ``-initrd``).
    """
    return textwrap.dedent(f"""\
        # Auto-generated by FastTrack — NixOS initramfs builder.
        {{ nixpkgs ? <nixpkgs> }}:

        let
          nixos = import (nixpkgs + "/nixos") {{
            configuration = {{ modulesPath, ... }}: {{
              imports = [
                {config_path}
                (modulesPath + "/profiles/qemu-guest.nix")
              ];
              boot.loader.grub.enable = false;
            }};
          }};

        in nixos.config.system.build.initialRamdisk
    """)
