from __future__ import annotations

import subprocess
import textwrap
from pathlib import Path

from rich.console import Console

from iter.nix import nix_wrap
from iter.pipeline import Stage, Context

console = Console()

# Nix expression that builds a NixOS disk image from a user-supplied config.
# Produces a qcow2 (default) or raw image via nixpkgs' make-disk-image.
_NIXOS_IMAGE_NIX = textwrap.dedent("""\
    # Auto-generated by FastTrack — do not edit.
    {{ nixpkgs ? <nixpkgs> }}:

    let
      pkgs = import nixpkgs {{}};
      lib  = pkgs.lib;

      nixos = import (nixpkgs + "/nixos") {{
        configuration = {{ modulesPath, ... }}: {{
          imports = [
            {config_path}
            (modulesPath + "/profiles/qemu-guest.nix")
          ];
          # Suppress GRUB — direct kernel boot via QEMU -kernel
          boot.loader.grub.enable = lib.mkDefault false;
        }};
      }};

      make-disk-image = import (nixpkgs + "/nixos/lib/make-disk-image.nix") {{
        inherit pkgs lib;
        config      = nixos.config;
        format      = "{format}";
        diskSize    = "{disk_size}";
        # Deterministic, no need for a bootloader in the image
        installBootLoader = false;
      }};

    in make-disk-image
""")


class RootfsStage(Stage):
    """
    Resolves the rootfs image to use for this iteration.

    Shared:         verifies the image exists, writes path to ctx.artifacts.
    Per-iteration:  builds the image (buildroot / NixOS) then writes the path.

    Writes to ctx.artifacts:
      "rootfs" → Path to the rootfs image (cpio.gz, ext4, qcow2, …)
    """

    def run(self, ctx: Context) -> None:
        cfg    = ctx.iteration_config
        gc     = ctx.global_config
        rootfs = cfg.rootfs

        if rootfs.get("shared"):
            self._use_shared(rootfs, gc, ctx)
        else:
            self._build(rootfs, cfg, gc, ctx)

    def _use_shared(self, rootfs: dict, gc, ctx: Context) -> None:
        path = gc.root / rootfs["path"]
        if not path.exists():
            raise FileNotFoundError(
                f"Shared rootfs not found: {path}\n"
                "Add an image to rootfs/ or update config.yaml."
            )
        console.print(f"    Using shared rootfs: [cyan]{path.name}[/cyan]")
        ctx.artifacts["rootfs"] = path

    def _build(self, rootfs: dict, cfg, gc, ctx: Context) -> None:
        rtype    = rootfs.get("type", "")
        out_dir  = gc.iter_dir(cfg.name) / "build" / "rootfs"
        out_dir.mkdir(parents=True, exist_ok=True)

        dispatch = {
            "buildroot": self._build_buildroot,
            "nixos":     self._build_nixos,
            "initramfs": self._build_initramfs,
            "alpine":    self._fetch_alpine,
        }

        builder = dispatch.get(rtype)
        if builder is None:
            raise ValueError(f"Unknown rootfs type: {rtype!r}")

        image_path = builder(rootfs, cfg, gc, out_dir)
        ctx.artifacts["rootfs"] = image_path

    def _build_buildroot(self, rootfs: dict, cfg, gc, out_dir: Path) -> Path:
        config = rootfs.get("config")
        if not config or not Path(config).exists():
            raise FileNotFoundError(f"Buildroot config not found: {config}")
        console.print("    Building rootfs with [cyan]buildroot[/cyan]...")

        make = f"make O={out_dir} BR2_DEFCONFIG={config}"
        cmd = nix_wrap(make, cfg.nix)
        subprocess.run(cmd, shell=True, check=True)

        image = out_dir / "images" / "rootfs.cpio.gz"
        if not image.exists():
            raise FileNotFoundError(f"Buildroot output not found: {image}")
        return image

    def _build_nixos(self, rootfs: dict, cfg, gc, out_dir: Path) -> Path:
        nix_config = rootfs.get("config")
        if not nix_config:
            raise FileNotFoundError("NixOS config path not specified in rootfs config")
        nix_config_path = Path(nix_config).resolve()
        if not nix_config_path.exists():
            raise FileNotFoundError(f"NixOS config not found: {nix_config_path}")

        fmt = rootfs.get("format", "qcow2")
        disk_size = str(rootfs.get("disk_size", "2048"))
        log_path = out_dir / "nixos-build.log"

        # Write the builder nix expression
        builder_nix = out_dir / "builder.nix"
        builder_nix.write_text(_NIXOS_IMAGE_NIX.format(
            config_path=nix_config_path,
            format=fmt,
            disk_size=disk_size,
        ))

        console.print(f"    Building NixOS {fmt} image... (log -> {log_path})")
        with open(log_path, "w") as log:
            result = subprocess.run(
                ["nix-build", str(builder_nix), "-o", str(out_dir / "result")],
                cwd=out_dir,
                stdout=log, stderr=subprocess.STDOUT,
            )
        if result.returncode != 0:
            console.print(f"[red]    NixOS build failed. See {log_path}[/red]")
            raise RuntimeError("NixOS rootfs build failed")

        # nix-build produces a symlink at out_dir/result -> /nix/store/...
        # The image file is named nixos.qcow2 or nixos.img depending on format.
        result_dir = out_dir / "result"
        for suffix in (f".{fmt}", ".qcow2", ".img", ".raw"):
            for candidate in result_dir.iterdir():
                if candidate.name.endswith(suffix):
                    console.print(f"    [green]NixOS rootfs:[/green] {candidate.name}")
                    return candidate

        # Fallback: single file in result
        files = [f for f in result_dir.iterdir() if f.is_file()]
        if len(files) == 1:
            console.print(f"    [green]NixOS rootfs:[/green] {files[0].name}")
            return files[0]

        raise FileNotFoundError(
            f"Could not find NixOS image in {result_dir}.\n"
            f"Contents: {[f.name for f in result_dir.iterdir()]}"
        )

    # Must provide a pre-built cpio.gz or extend this method
    def _build_initramfs(self, rootfs: dict, cfg, gc, out_dir: Path) -> Path:
        image = out_dir / "rootfs.cpio.gz"
        if not image.exists():
            raise FileNotFoundError(
                f"initramfs not found at {image}.\n"
                "Build a busybox initramfs and place it there, or use a shared rootfs."
            )
        return image

    def _fetch_alpine(self, rootfs: dict, cfg, gc, out_dir: Path) -> Path:
        image = out_dir / "alpine.tar.gz"
        if not image.exists():
            raise FileNotFoundError(
                f"Alpine rootfs not found at {image}.\n"
                "Download from https://alpinelinux.org/downloads/ (Mini Root Filesystem)."
            )
        return image
